# -*- coding: utf-8 -*-
from . import ir_http
from . import res_partner
from . import res_company
from . import res_users
from . import it_support_end_user
from . import it_customer_device
from . import it_support_type
from . import it_support_duty_schedule
from . import it_support_session
from . import it_support_session_participant
from . import it_support_ticket
from . import it_support_session_end_wizard
from . import it_support_ticket_reply_wizard
from . import it_support_monthly_summary
from . import it_support_generate_summary_wizard
from . import it_support_agent_commission_wizard
from . import it_support_agent_payroll
from . import it_support_agent_payroll_generate_wizard
from . import it_support_agent_device
from . import it_support_sla
from . import it_support_fcm_service
from . import it_support_booking_request
from . import it_expense_category
from . import account_move
from . import it_project_project
from . import it_project_task
